//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantasyFootball.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FantasyFootballEntities : DbContext
    {
        public FantasyFootballEntities()
            : base("name=FantasyFootballEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_ff_players> tbl_ff_players { get; set; }
        public DbSet<tbl_ff_matchups_2013> tbl_ff_matchups_2013 { get; set; }
        public DbSet<tbl_ff_stats_weekly_players> tbl_ff_stats_weekly_players { get; set; }
    }
}
