//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantasyFootball.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ff_matchups_2013
    {
        public int MatchUpId { get; set; }
        public string Team { get; set; }
        public string Opponent { get; set; }
        public Nullable<int> Week { get; set; }
        public Nullable<bool> IsHome { get; set; }
        public Nullable<bool> IsBye { get; set; }
    }
}
