//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantasyFootball.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ff_stats_weekly_players
    {
        public int PlayerStatsWeeklyId { get; set; }
        public string Espn { get; set; }
        public string Cbs { get; set; }
        public string Nfl { get; set; }
        public string Roto { get; set; }
        public string Yahoo { get; set; }
        public Nullable<int> PassAtt { get; set; }
        public Nullable<int> PassComp { get; set; }
        public Nullable<int> PassYds { get; set; }
        public Nullable<int> PassTDs { get; set; }
        public Nullable<int> PassINTs { get; set; }
        public Nullable<int> Receptions { get; set; }
        public Nullable<int> RecYards { get; set; }
        public Nullable<int> RecTDs { get; set; }
        public Nullable<int> Rushes { get; set; }
        public Nullable<int> RushYds { get; set; }
        public Nullable<int> RushTDs { get; set; }
        public Nullable<int> DefTackles { get; set; }
        public Nullable<int> DefAssists { get; set; }
        public Nullable<int> DefINTs { get; set; }
        public Nullable<int> DefFFs { get; set; }
        public Nullable<decimal> DefSacks { get; set; }
        public Nullable<int> Week { get; set; }
    }
}
