//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantasyFootball.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ff_matchups
    {
        public int MatchupId { get; set; }
        public string HomeTeam { get; set; }
        public string AwayTeam { get; set; }
        public int Season { get; set; }
        public int Week { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
